In [ ]:
# Bollywood Movie Success Prediction & Recommendation System

## Author
Pragya Gupta

## Objective

This project aims to analyze Bollywood movie data using statistics and machine learning.

The project includes:

- Exploratory Data Analysis
- Feature Engineering
- Statistical Hypothesis Testing
- Revenue Prediction
- Hit/Flop Prediction
- Movie Segmentation using K-Means
- Content-Based Movie Recommendation System

## Dataset

The dataset contains information regarding Bollywood movies including

- Budget
- Revenue
- Genre
- Director
- Lead Star
- Number of Screens
- Release Period
- Franchise Status
- Remake Status

## Libraries

- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-Learn
- SciPy

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import (
    pearsonr,
    chi2_contingency,
    ttest_ind,
    f_oneway
)

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

from sklearn.linear_model import (
    LinearRegression,
    LogisticRegression
)

from sklearn.tree import (
    DecisionTreeClassifier,
    DecisionTreeRegressor
)

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from sklearn.cluster import KMeans

from sklearn.decomposition import PCA

from sklearn.metrics.pairwise import cosine_similarity

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    auc,
    silhouette_score
)

In [3]:
df = pd.read_csv("../data/movies.csv")

In [4]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.head()

Rows : 1698
Columns : 14

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Name          1698 non-null   str
 1   Release_Period      1698 non-null   str
 2   Whether_Remake      1698 non-null   str
 3   Whether_Franchise   1698 non-null   str
 4   Genre               1698 non-null   str
 5   New_Actor           1698 non-null   str
 6   New_Director        1698 non-null   str
 7   New_Music_Director  1698 non-null   str
 8   Lead_Star           1698 non-null   str
 9   Director            1698 non-null   str
 10  Music_Director      1698 non-null   str
 11  Number_of_Screens   1698 non-null   int64
 12  Revenue(INR)        1698 non-null   int64
 13  Budget(INR)         1698 non-null   int64
dtypes: int64(3), str(11)
memory usage: 185.8 KB

In [6]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Movie_Name,1698,1695,Game,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Release_Period,1698,2,Normal,1064,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Whether_Remake,1698,2,No,1627,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Whether_Franchise,1698,2,No,1616,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genre,1698,14,drama,639,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New_Actor,1698,2,No,1243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New_Director,1698,2,No,882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New_Music_Director,1698,2,No,1144,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lead_Star,1698,764,Akshay Kumar,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Director,1698,1048,Ram Gopal Verma,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Music_Director,1698,630,Pritam,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number_of_Screens,1698.0,NaN,NaN,NaN,553.831567,782.951839,1.0,30.0,200.0,800.0,4600.0
Revenue(INR),1698.0,NaN,NaN,NaN,150167388.103651,243483827.621758,325000.0,15000000.0,55000000.0,190000000.0,2100000000.0
Budget(INR),1698.0,NaN,NaN,NaN,237728726.759717,613439812.258645,7250.0,1150000.0,12400000.0,177832500.0,8016120000.0

In [7]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean() * 100, 2)
})

missing

                    Missing Values  Percentage
Movie_Name                       0         0.0
Release_Period                   0         0.0
Whether_Remake                   0         0.0
Whether_Franchise                0         0.0
Genre                            0         0.0
New_Actor                        0         0.0
New_Director                     0         0.0
New_Music_Director               0         0.0
Lead_Star                        0         0.0
Director                         0         0.0
Music_Director                   0         0.0
Number_of_Screens                0         0.0
Revenue(INR)                     0         0.0
Budget(INR)                      0         0.0

In [8]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 2

In [9]:
df = df.drop_duplicates()

print(df.shape)

(1696, 14)